[env]
TERM = "xterm-256color"

[font]
size = 11

[font.normal]
family = "MonaspiceNe Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[window]
decorations = "none"
startup_mode = "Maximized"

[window.padding]
x = 0
y = 0

# Github Dark Colors for Alacritty

# Github Dark Tritanopia Colors for Alacritty

[colors]

  # Default colors
  [colors.primary]
  background = "0x0d1117"
  foreground = "0xc9d1d9"

  # Cursor colors
  # These will only be used when the `custom_cursor_colors` field is set to `true`.
  [colors.cursor]
  text = "0x0d1117"
  cursor = "0xc9d1d9"

  # Normal colors
  [colors.normal]
  black = "0x484f58"
  red = "0xff7b72"
  green = "0x58a6ff"
  yellow = "0xd29922"
  blue = "0x58a6ff"
  magenta = "0xbc8cff"
  cyan = "0x39c5cf"
  white = "0xb1bac4"

  # Bright colors
  [colors.bright]
  black = "0x6e7681"
  red = "0xffa198"
  green = "0x79c0ff"
  yellow = "0xe3b341"
  blue = "0x79c0ff"
  magenta = "0xbc8cff"
  cyan = "0x39c5cf"
  white = "0xb1bac4"
