[env]
TERM = "alacritty"

[font]
size = 11

[colors]
draw_bold_text_with_bright_colors = true
[font.normal]
family = "MonaspiceNe Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[window]
decorations = "none"
startup_mode = "Maximized"
opacity = 1.0
dynamic_title = true

[window.padding]
x = 0
y = 0

