[env]
TERM = "xterm-256color"

[font]
size = 11

[font.normal]
family = "MonaspiceNe Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[window]
decorations = "none"
startup_mode = "Maximized"

[window.padding]
x = 0
y = 0
