return {
  { require "plugins.nvim_dap" },
  --  { require "plugins.nvim_dap_rr" },
  { require "plugins.rustaceanvim" },
  { require "plugins.nvim_dap_ui" },
  { require "plugins.conform" },
  { require "plugins.crates" },
  { require "plugins.inlaly_hints" },
  { require "plugins.mason" },
  { require "plugins.nvim_lspconfig" },
  { require "plugins.nvim_web_icons" },
  { require "plugins.outline" },
  { require "plugins.telescope" },
  { require "plugins.todo_comments" },
  { require "plugins.trouble" },
  { require "plugins.typr" },
}
